name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  call-reusable:
    uses: 3592917/ci-templates/.github/workflows/flutter-reusable.yml@main
    with:
      channel: 'stable'
      run_ios: false
      run_android_build: true
      upload_apk: false
      run_codecov: false
