// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACaCnvpPVadwhfZdK8zEZ-VeXrYXwzEvg',
    appId: '1:577726995056:web:f7f2e73de53f3eda9df2b5',
    messagingSenderId: '577726995056',
    projectId: 'wardrobe-5f0e2',
    authDomain: 'wardrobe-5f0e2.firebaseapp.com',
    storageBucket: 'wardrobe-5f0e2.firebasestorage.app',
    measurementId: 'G-3FSC095XF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFTJBJi9Zj3IzSVxtwOzCVx5UQjDsbgn0',
    appId: '1:577726995056:android:902808793cda10489df2b5',
    messagingSenderId: '577726995056',
    projectId: 'wardrobe-5f0e2',
    storageBucket: 'wardrobe-5f0e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2S8pdcor2w_Izper8CXPSk-ta2qVAw9E',
    appId: '1:577726995056:ios:e63be5d53847ab4d9df2b5',
    messagingSenderId: '577726995056',
    projectId: 'wardrobe-5f0e2',
    storageBucket: 'wardrobe-5f0e2.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2S8pdcor2w_Izper8CXPSk-ta2qVAw9E',
    appId: '1:577726995056:ios:e63be5d53847ab4d9df2b5',
    messagingSenderId: '577726995056',
    projectId: 'wardrobe-5f0e2',
    storageBucket: 'wardrobe-5f0e2.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACaCnvpPVadwhfZdK8zEZ-VeXrYXwzEvg',
    appId: '1:577726995056:web:cf61797645ee50899df2b5',
    messagingSenderId: '577726995056',
    projectId: 'wardrobe-5f0e2',
    authDomain: 'wardrobe-5f0e2.firebaseapp.com',
    storageBucket: 'wardrobe-5f0e2.firebasestorage.app',
    measurementId: 'G-XE8HJ27CXN',
  );
}
